# list of smash characters
CHARACTERS = [
    'Mario',
    'Donkey Kong',
    'Link',
    'Samus',
    'Yoshi',
    'Kirby',
    'Fox McCloud',
    'Pikachu',
    'Dark Samus*',
    'Luigi',
    'Ness',
    'Captain Falcon',
    'Jigglypuff',
    'Princess Peach',
    'Princess Daisy*',
    'Bowser',
    'Ice Climbers',
    'Sheik',
    'Princess Zelda',
    'Dr. Mario',
    'Pichu',
    'Falco Lombardi',
    'Marth',
    'Lucina*',
    'Young Link',
    'Ganondorf',
    'Mewtwo',
    'Roy',
    'Chrom*',
    'Mr. Game & Watch',
    'Meta Knight',
    'Pit',
    'Dark Pit*',
    'Zero Suit Samus',
    'Wario',
    'Solid Snake',
    'Ike',
    'Pokémon Trainer',
    'Squirtle',
    'Ivysaur',
    'Charizard',
    'Diddy Kong',
    'Lucas',
    'Sonic',
    'King Dedede',
    'Pikmin and Olimar',
    'Lucario',
    'R.O.B.',
    'Toon Link',
    "Wolf O'Donnell",
    'Villager',
    'Mega Man',
    'Wii Fit Trainer',
    'Rosalina and Luma',
    'Little Mac',
    'Greninja',
    'Mii Brawler',
    'Mii Swordfighter',
    'Mii Gunner',
    'Palutena',
    'Pac-Man',
    'Robin',
    'Shulk',
    'Bowser Jr.',
    'Duck Hunt',
    'Ryu',
    'Ken Masters*',
    'Cloud Strife',
    'Corrin',
    'Bayonetta',
    'Inkling',
    'Ridley',
    'Simon Belmont',
    'Richter Belmont*',
    'King K. Rool',
    'Isabelle',
    'Incineroar',
    'Piranha Plant',
    'Joker',
    'Hero',
    'Banjo and Kazooie',
    'Terry',
    'Byleth',
    'Min Min',
    'Steve',
    'Sephiroth',
    'Pyra/Mythra',
    'Kazuya Mishima',
    'Sora',
]
